import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MyComponent from "./table";
import { ApolloProvider } from "@apollo/client";
import client from "./api/apolloClient";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Oi Source</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ApolloProvider client={client}>
          <MyComponent></MyComponent>
        </ApolloProvider>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
